name: pgp run

# on:
#   schedule:
#     - cron: "0 13 * * *"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          
      - name: install python packages
        run: |
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        run: python src/core.py

      - name: create json
        id: create-json-1
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: 'service_account'
          json: ${{ secrets.SERVICE }}
          dir: 'src/'
      - name: execute py script
        echo ${{ env.working-directory }}
        run: python src/sheet_update.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Updated gems.csv" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SOME_SECRET }}
          branch: main 
