name: pgp run

on: push
  # schedule: 
  # - cron: "0 */6 * * *"  # every 6-ish hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install python packages
        run: |
          pip install -r requirements.txt
          
      - name: execute main.py
        run: python src/main.py

      - name: create json
        id: create-json-1
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: 'service_account.json'
          json: ${{ secrets.SERVICE }}
          dir: 'output/'

      - name: execute sheet_update.py
        run: python src/sheet_update.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Updated gems.csv" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main 
