name: Go Hello

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run_binary:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Binary
      run: ./hello

